events { 
    worker_connections 1024; 
    }

http {
    upstream backend_api {
        server backend:8000;
    }

    # 1. Redirigir todo el tráfico HTTP a HTTPS
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # 2. Configuración del Proxy Reverso con SSL
    server {
        listen 443 ssl;
        server_name localhost;

        # Certificados que generamos
        ssl_certificate /etc/nginx/certs/selfsigned.crt;
        ssl_certificate_key /etc/nginx/certs/selfsigned.key;

        location / {
            proxy_pass http://backend_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}